### ISSUE TITLE
115登陆接口改了

### ISSUE THREAD

**Issue by zeroleo12345** [shichao-an/115wangpan#31]
115登陆url和参数好像都改了, 导致登陆不上

**Comment by zeroleo12345** [comment]
研究了现在版本的js，这函数window.browserInterface.ParamEncrypt像是115浏览器自带的啊，有点难破。

    function f(a, b, c, f, g, h, i, j, k) {
        try {
            if (window.browserInterface.ParamEncrypt) return void e(a, b, h)
        } catch (l) {}

**Comment by zeroleo12345** [comment]
这些还可以用, 逆向115浏览器的太痛苦了。
                                    <div id="js-quick_login_box" class="login-oauth" style="display: none;">
                                        <h3>使用合作网站帐号登录：</h3>
                                        <ul>
                                            <li><a href="http://passport.115.com/?ct=open_login&t=wechat" title="使用微信登录"><i class="ico-oauth oau-wx"></i>微信</a></li>
                                            <li><a href="http://passport.115.com/?ct=open_login&t=sina" title="使用新浪微博登录"><i class="ico-oauth oau-sina"></i>微博</a></li>
                                            <li><a href="http://passport.115.com/?ct=open_login&t=qq" title="使用腾讯QQ登录"><i class="ico-oauth oau-qq"></i>QQ</a></li>
                                        </ul>

                                        <div rel="more" class="tit-more"><span>其他</span><s></s></div>
                                        <div rel="more_box" class="lo-more" style="display: none;">
                                            <div class="cont-box">
                                                <a target="_blank" href="http://passport.115.com/?ct=open_login&t=renren"><i class="lom-renren"></i><span>人人网</span></a>
                                                <a target="_blank" href="http://passport.115.com/?ct=open_login&t=tqq"><i class="lom-tencent"></i><span>腾讯微博</span></a>
                                                <a target="_blank" href="http://passport.115.com/?ct=open_login&t=baidu"><i class="lom-baidu"></i><span>百度</span></a>
                                                <a target="_blank" href="http://passport.115.com/?ct=open_login&t=alipay"><i class="lom-alipay"></i><span>支付宝</span></a>
                                                <a target="_blank" href="http://passport.115.com/?ct=open_login&t=surfing"><i class="lom-tianyi"></i><span>天翼</span></a>
                                            </div>
                                            <div class="bottom-box">请登录后尽快绑定手机和设置密码，我们将只保留微信、微博、QQ登录</div>
                                        </div>
                                    </div>
                                </div>

**Comment by raycraft** [comment]
此问题能够修复吗？

**Comment by ieiayaobb** [comment]
看上去换了加密算法，包装在了他的客户端内，chrome又不支持密码登陆了，所以这问题无解了？

**Comment by shichao-an** [comment]
115强制用户用115浏览器，目前没有好方法。

**Comment by luoyi** [comment]
能否提取二维码，登陆的时候，让用户用手机扫描二维码。做不到全自动，做到半自动也可以。

**Comment by luoyi** [comment]
或者是让用户用浏览器登陆完，提供一个导出 cookie 的方式，然后直接用 cookie 文件做后续的操作。

**Comment by stulcj** [comment]
现在登陆不了，每次登陆都会有这个提示：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "u115\api.py", line 315, in login
    raise AuthenticationError(msg)
u115.api.AuthenticationError: Account does not exist.

**Comment by stulcj** [comment]
能否在程序中模拟115浏览器登陆呢？

**Comment by shichao-an** [comment]
@stulcj 目前还没有找到解决办法

**Comment by xxxNull** [comment]
手动登陆一次拿cookies 可以取数据

**Comment by ieiayaobb** [comment]
@Karblue 能详细说说吗？

**Comment by xxxNull** [comment]
@ieiayaobb 就是你手动用115的二维码或者浏览器登陆一次 浏览器F12看网络栏的cookies 复制过来.以后的操作115都只用这个cookie 就行了 . 115的离线api 直接连cookie 都没用 用的一个sign 参数控制的.还是永久的. 只要sign 验证正确就可以添加离线任务

**Comment by xxxNull** [comment]
记录一下 。 关键加密算法存在于115浏览器的browserInterface.ParamEncrypt 中  需要逆向 目前确定貌似使用AES + SHA 加密 参数如下:
callback("base64加密后的登陆数据", "c4cc2c3df3c8feff55fc645020408a7b", "1ce86b8560b2e9ea27b076dcf64f7a79", "1452592218");
剩下俩参数应该时按时间戳算出来的什么东西

**Comment by jin10086** [comment]
User-Agent:Mozilla / 5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 115Browser/6.0.0

把头文件改成115浏览器不知道行不行，回去试试看

**Comment by xxxNull** [comment]
@kimg1234 并没有什么卵用

**Comment by jin10086** [comment]
@Karblue  cookies 复制过来还是不行呀 ，你cookies复制过来成功了么?可以吧代码发给我下么？
admin@wuaics.cn

**Comment by ieiayaobb** [comment]
@kimg1234 你从浏览器里拷贝CID,SEID,UID到cookies就可以访问了，不知道是不是还能用这个API提供的接口
